plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.0.0-beta4'
    id 'maven-publish'
}

compileJava {
    options.encoding = 'UTF-8'
}

group 'pl.nightdev701'
version = 'SNAPSHOT-3.0.1'

repositories {
    maven {
        url 'https://jitpack.io'
    }

    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
    implementation 'com.mysql:mysql-connector-j:9.2.0'

    // https://mvnrepository.com/artifact/org.postgresql/postgresql
    implementation 'org.postgresql:postgresql:42.7.5'

    // https://mvnrepository.com/artifact/com.j256.ormlite/ormlite-jdbc
    implementation 'com.j256.ormlite:ormlite-jdbc:6.1'

    // https://mvnrepository.com/artifact/redis.clients/jedis
    implementation 'redis.clients:jedis:5.3.0-beta1'

    // https://mvnrepository.com/artifact/org.apache.sshd/sshd-core
    implementation 'org.apache.sshd:sshd-core:2.14.0'

    // https://mvnrepository.com/artifact/com.google.code.gson/gson
    implementation 'com.google.code.gson:gson:2.11.0'

    // https://mvnrepository.com/artifact/com.unboundid/unboundid-ldapsdk
    implementation 'com.unboundid:unboundid-ldapsdk:7.0.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

jar {
    println("Build project, git-hash: " + 'git rev-parse --verify --short HEAD'.execute().text.trim())
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from {
        subprojects.collect { it.sourceSets.main.output }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = uri("https://jitpack.io")
        }
    }
}
